version: "2.4"
services:
  api:
    image: ${API_IMAGE}
    environment:
      - APP_NAME=laravel
      - APP_ENV=local
      - APP_KEY=base64:AH8NCjdy8jkyl8aHHZCa5Ox9bjJvo7yJDzG9DwmbLx8=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=log
    depends_on:
      mysql-test:
        condition: service_healthy
    command: sh -c "php artisan migrate --force && php artisan test"

  mysql-test:
    image: ${MYSQL_IMAGE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=secret
